
#ifndef __BSD_SYSCALLS
#define __BSD_SYSCALLS

#define BSD_SYS_EXIT 1
#define BSD_SYS_FORK 2
#define BSD_SYS_READ 3
#define BSD_SYS_WRITE 4

#define BSD_SYS_OPEN 5
#define BSD_SYS_CLOSE 6
#define BSD_SYS_WAIT4 7

#define BSD_SYS_CHDIR 12

#define BSD_SYS_OLD_LSEEK 19

#define BSD_SYS_SETUID 23
#define BSD_SYS_GETUID 24
#define BSD_SYS_GETEUID 25

#define BSD_SYS_RECVFROM 29
#define BSD_SYS_ACCEPT 30
#define BSD_SYS_GETPEERNAME 31

#define BSD_SYS_GETEGID 43

#define BSD_SYS_SETGID 181
#define BSD_SYS_SETEGID 182
#define BSD_SYS_SETEUID 183
#define BSD_SYS_GETGID 47

#define BSD_SYS_SETREUID 126
#define BSD_SYS_SETREGID 127

#define BSD_SYS_SETGROUPS 80

#define BSD_SYS_SENDTO 133
#define BSD_SYS_SHUTDOWN 134

#define BSD_SYS_SETRESUID 311
#define BSD_SYS_GETRESUID 360

#define BSD_SYS_SETRESGID 312
#define BSD_SYS_GETRESGID 361

#define BSD_SYS_KILL 37
#define BSD_SYS_GETPPID 39

#define BSD_SYS_EXECVE 59

#define BSD_SYS_MPROTECT 74

#define BSD_SYS_DUP2 90

#define BSD_SYS_SOCKET 97
#define BSD_SYS_CONNECT 98
#define BSD_SYS_BIND 104
#define BSD_SYS_SETSOCKOPT 105
#define BSD_SYS_LISTEN 106

#define BSD_SYS_LSEEK 199

#define BSD_SYS_NANOSLEEP 240
#define BSD_SYS_SIGACTION 416

#endif
